# Configuration for static files
assets_dir:       ./assets
destination:      ./build

# Setup
title:            ayalava2
tagline:          ''
description:      ''
url:              arvindyalavarti.com
baseurl:          /
