source              : ./build
destination         : ./template

# Setup
title:            ayalava2
tagline:          ''
description:      ''
url:              arvindyalavarti.com
baseurl:          /

plugins:
  - jekyll-environment-variables
